import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Navbar from "@/components/ui/Navbar";
import { Toaster } from 'sonner';
import { currentUser } from "@clerk/nextjs/server";
import Sidebar from "@/components/ui/Sidebar";
import { LoadingOverlayProvider, LoadingOverlay } from "@/components/ui/LoadingOverlay";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await currentUser();
  return (
    <ClerkProvider>
      <LoadingOverlayProvider>
        <html lang="en">
          <body className={inter.className}>
            <Navbar />
            <Toaster position="top-center" richColors />
            <div className="flex">
              <Sidebar authUser={user ? JSON.parse(JSON.stringify(user)) : null} />
              <main className="flex-1 ml-72 transition-all duration-300 relative">
                <LoadingOverlay isLoading={false} />
                {children}
              </main>
            </div>
          </body>
        </html>
      </LoadingOverlayProvider>
    </ClerkProvider>
  );
}
